local wezterm = require("wezterm")

-- https://github.com/yutkat/dotfiles/blob/main/.config/wezterm/wezterm.lua
local config = {
    check_for_updates = true,
    -- color_scheme = "Catppuccin Mocha",
	color_scheme = "Tango (terminal.sexy)",
	-- color_scheme = "Github Dark",
	-- color_scheme = "Dark Pastel",
	-- color_scheme = "Sakura",
    inactive_pane_hsb = {
        hue = 1.0,
        saturation = 1.0,
        brightness = 1.0,
    },
    default_prog = { '/bin/zsh', '-l' },
    -- font = wezterm.font_with_fallback { { family = 'Roboto Mono', italic = false}, 'SFMono Nerd Font', 'Hack Nerd Font'},
	font = wezterm.font('Roboto Mono', {italic = false}),
    font_size = 18.0,
    launch_menu = {},
	initial_cols = 120,
	initial_rows = 36,
    leader = { key="a", mods="CTRL" },
    disable_default_key_bindings = false,
	enable_scroll_bar = true,
    keys = {
        -- Send "CTRL-A" to the terminal when pressing CTRL-A, CTRL-A
        { key = "a", mods = "LEADER|CTRL",  action=wezterm.action{SendString="\x01"}},
        { key = "-", mods = "LEADER",       action=wezterm.action{SplitVertical={domain="CurrentPaneDomain"}}},
        { key = "\\",mods = "LEADER",       action=wezterm.action{SplitHorizontal={domain="CurrentPaneDomain"}}},
        { key = "z", mods = "LEADER",       action="TogglePaneZoomState" },
        { key = "c", mods = "LEADER",       action=wezterm.action{SpawnTab="CurrentPaneDomain"}},
        { key = "h", mods = "LEADER",       action=wezterm.action{ActivatePaneDirection="Left"}},
        { key = "j", mods = "LEADER",       action=wezterm.action{ActivatePaneDirection="Down"}},
        { key = "k", mods = "LEADER",       action=wezterm.action{ActivatePaneDirection="Up"}},
        { key = "l", mods = "LEADER",       action=wezterm.action{ActivatePaneDirection="Right"}},
        { key = "H", mods = "LEADER|SHIFT", action=wezterm.action{AdjustPaneSize={"Left", 5}}},
        { key = "J", mods = "LEADER|SHIFT", action=wezterm.action{AdjustPaneSize={"Down", 5}}},
        { key = "K", mods = "LEADER|SHIFT", action=wezterm.action{AdjustPaneSize={"Up", 5}}},
        { key = "L", mods = "LEADER|SHIFT", action=wezterm.action{AdjustPaneSize={"Right", 5}}},
        { key = "1", mods = "LEADER",       action=wezterm.action{ActivateTab=0}},
        { key = "2", mods = "LEADER",       action=wezterm.action{ActivateTab=1}},
        { key = "3", mods = "LEADER",       action=wezterm.action{ActivateTab=2}},
        { key = "4", mods = "LEADER",       action=wezterm.action{ActivateTab=3}},
        { key = "5", mods = "LEADER",       action=wezterm.action{ActivateTab=4}},
        { key = "6", mods = "LEADER",       action=wezterm.action{ActivateTab=5}},
        { key = "7", mods = "LEADER",       action=wezterm.action{ActivateTab=6}},
        { key = "8", mods = "LEADER",       action=wezterm.action{ActivateTab=7}},
        { key = "9", mods = "LEADER",       action=wezterm.action{ActivateTab=8}},
        { key = "&", mods = "LEADER|SHIFT", action=wezterm.action{CloseCurrentTab={confirm=true}}},
        { key = "x", mods = "LEADER",       action=wezterm.action{CloseCurrentPane={confirm=true}}},
        { key = "n", mods="SHIFT|CTRL",     action="ToggleFullScreen" },
        { key = "v", mods="SHIFT|CTRL",     action=wezterm.action{PasteFrom="Clipboard"}},
        { key = "c", mods="SHIFT|CTRL",     action=wezterm.action{CopyTo = "Clipboard"}},
    },
    set_environment_variables = {},

	-- customize
	use_fancy_tab_bar = false,
	-- hide_tab_bar_if_only_one_tab = true,
	-- jwindow_decorations = "RESIZE",
	-- show_new_tab_button_in_tab_bar = false,
	window_background_opacity = 0.9,
	macos_window_background_blur = 70,
	text_background_opacity = 0.9,
	adjust_window_size_when_changing_font_size = false,
}

return config
